# spring.datasource.url=jdbc:postgresql://localhost:5432/project_generator
# spring.datasource.username=postgres
# spring.datasource.password=591337

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# mistral.api.key=wJMryvf8l7DWBz4RFfhOSvW068oT64RD


# jdbc:postgresql://db.ncifvohzrhjllsrusxov.supabase.co:5432/postgres?user=postgres&password=[YOUR-PASSWORD]

# spring.datasource.url=${DATABASE_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
mistral.api.key=${MISTRAL_API_KEY}